In [9]:
import pandas as pd
dfs = pd.read_excel("trade.xlsx", sheet_name=["Торговля", "Товар", "Магазин"])

In [10]:
trades = dfs["Торговля"]
goods = dfs["Товар"]
shops = dfs["Магазин"]

In [11]:
trades.head()

,ID\nоперации,Дата,Магазин,Артикул,Операция,"Количество\nупаковок, шт",Цена руб/шт
0,1,2021-06-01,М01,1,Поставка,20,187
1,2,2021-06-01,М01,2,Поставка,40,89
2,3,2021-06-01,М01,4,Продажа,21,19
3,4,2021-06-01,М01,5,Поставка,50,39
4,5,2021-06-01,М01,6,Продажа,26,270

In [12]:
goods.head()

,Артикул,Отдел,Наименование товара,Ед изм,Количество\nв упаковке,Поставщик
0,1,Молоко,Сливки 35% для взбивания,литр,0.5,Молокозавод №1
1,2,Молоко,Молоко безлактозное,литр,0.5,Экопродукты
2,3,Молоко,"Кефир 3,2%",литр,1.0,Молокозавод №2
3,4,Бакалея,Соль каменная помол №1,кг,1.0,Продбаза
4,5,Бакалея,Сахар песок белый,кг,1.0,"""Чай-кофе-сахар"""

In [13]:
shops.head()

  ID магазина        Район
0         М01     Заречный
1         М02     Заречный
2         М03     Заречный
3         М04  Октябрьский
4         М05  Октябрьский

In [19]:


df = pd.merge(pd.merge(trades, goods, left_on="Артикул", right_on="Артикул"), shops, left_on="Магазин", right_on="ID магазина")
df["Отдел"].unique()

array(['Молоко', 'Бакалея', 'Мясная гастрономия'], dtype=object)

In [ ]:
target = df[(df["Район"]=="Центральный") & (df["Отдел"]=="Бакалея")]
df["profit"] =

,ID\nоперации,Дата,Магазин,Артикул,Операция,"Количество\nупаковок, шт",Цена руб/шт,Отдел,Наименование товара,Ед изм,Количество\nв упаковке,Поставщик,ID магазина,Район
216,217,2021-06-01,М08,8,Продажа,585,72,Бакалея,Хлопья овсяные Геркулес,кг,0.5,Продбаза,М08,Центральный
220,221,2021-06-01,М08,13,Продажа,466,56,Бакалея,Макароны перья,кг,0.5,Макаронная фабрика,М08,Центральный
225,226,2021-06-01,М08,22,Поставка,50,315,Бакалея,Фунчоза,кг,0.5,Экопродукты,М08,Центральный
228,229,2021-06-01,М08,37,Продажа,428,73,Бакалея,Хлопья 4 злака,кг,0.5,Продбаза,М08,Центральный
231,232,2021-06-01,М08,41,Поставка,300,126,Бакалея,Рис круглозерный,кг,1.0,Продбаза,М08,Центральный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87888,87889,2021-06-30,М94,50,Поставка,100,99,Бакалея,Сахар демерара коричневый,кг,1.0,"""Чай-кофе-сахар""",М94,Центральный
87891,87892,2021-06-30,М94,54,Продажа,575,133,Бакалея,Кукурузные хлопья,кг,0.5,Продбаза,М94,Центральный
87892,87893,2021-06-30,М94,56,Поставка,200,79,Бакалея,Крупа пшено,кг,1.0,Продбаза,М94,Центральный
87893,87894,2021-06-30,М94,57,Продажа,333,370,Бакалея,Кофе растворимый,кг,0.2,"""Чай-кофе-сахар""",М94,Центральный
87896,87897,2021-06-30,М94,62,Продажа,61,116,Бакалея,Чечевица красная,кг,1.0,Экопродукты,М94,Центральный